#!/bin/sh

# Install neovim's plug
if [ ! -e ~/.local/share/nvim/site/autoload/plug.vim ]; then
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    nvim +PlugInstall +qa
fi

# Install oh-my-zsh
if [ ! -d ~/.oh-my-zsh ]; then
    CHSH=no RUNZSH=no sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Install ultimate vimrc
if [ ! -d ~/.vim_runtime/vimrcs ]; then
    git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime && sh ~/.vim_runtime/install_basic_vimrc.sh
fi

# Install tmux's tpm
if [ ! -d ~/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

ln -s ~/.vim_runtime/vimrcs/basic.vim ~/.config/nvim/basic.vim

# Install composer
curl --create-dirs https://getcomposer.org/download/2.2.0/composer.phar -o ~/.local/bin/composer
chmod 744 ~/.local/bin/composer

# Install Symfony CLI
curl -sS https://get.symfony.com/cli/installer | bash

