#! /bin/sh

## Coloring
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
xrdb ~/.Xresources
export COLOR=$(shuf -n1 -e ~/.colors/*.enable)
SHORTCOLOR=$(echo $COLOR | sed "s@.*/@@")
xrdb -merge $COLOR
getcolors

sxhkd &
~/.dotfiles/linux/.config/polybar/launch.sh &
compton -b &

bspc monitor -d main web comm dev code term play

bspc config border_width         4
bspc config window_gap          24

bspc config bottom_padding 4
bspc config normal_border_color  "$BLACK"
bspc config focused_border_color "$BLUE"
bspc config active_border_color  "$MAGENTA"
bspc config urgent_border_color	 "$RED"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
